Use local servers to generate config file
skycoin/skywire pull request #1003
Opened 2021-11-15 12:38 UTC by mrpalide

Did you run `make format && make check`? Yes

Fixes #423

 Changes:	
- Add flag `-l` to use addresses in `localServers.json` file as services address.

How to test this PR:
- `make build`
- `./skywire-cli config gen -l`
- check `skywire-config.json` for local servers addresses

2021-11-15 15:21 UTC, jdknives requested changes

2021-11-15 15:21 UTC, jdknives commented on cmd/skywire-cli/commands/config/gen.go
> +	localConfig        bool
We can rename this to `dmsgHttp` imo as this a separate feature now.

2021-11-15 15:21 UTC, jdknives commented on cmd/skywire-cli/commands/config/gen.go
> +	genConfigCmd.Flags().BoolVarP(&localConfig, "local", "l", false, "use local servers PK instead global")
Consequently this be `connect to Skywire Services via dmsg`.

2021-11-17 10:28 UTC, ersonp approved these changes

2021-11-17 11:19 UTC, jdknives approved these changes

2021-11-17 11:19 UTC, merged