Implemented backoff for transport reconnection
skycoin/skywire pull request #148
Opened 2020-02-03 07:59 UTC by Kifen

Did you run `make format && make check`?
yes
Fixes #68  	

 Changes:	
-	updated transport connection redial with a backoff implementation

How to test this PR:
Establish a connection between two visors, then shut down one visor

2020-02-03 16:34 UTC, nkryuchkov requested changes

2020-02-03 16:34 UTC, nkryuchkov commented on pkg/router/router_test.go
> +	"github.com/SkycoinProject/skywire-mainnet/internal/netutil"
Could you please move this line and line 15 below to corresponding import blocks?

2020-02-03 16:34 UTC, nkryuchkov commented on pkg/transport/managed_transport.go
> +// redialConn redials an underlying connection using an exponetial backoff
`exponetial` => `exponential`

2020-02-03 16:34 UTC, nkryuchkov commented on pkg/transport/manager_test.go
> +	"github.com/SkycoinProject/skywire-mainnet/internal/netutil"
Could you please move 12 and 14 to corresponding blocks?

2020-02-03 16:34 UTC, nkryuchkov commented on pkg/visor/visor_test.go
> +	"github.com/SkycoinProject/skywire-mainnet/internal/netutil"
Could you please move it to corresponding block?

2020-02-03 16:34 UTC, nkryuchkov commented on pkg/transport/managed_transport.go
>  				if mt.conn == nil {
I would write `if mt.conn == nil && !mt.retrier.alive` to descrease indentation

2020-02-05 07:57 UTC, Kifen commented on pkg/router/router_test.go
> +	"github.com/SkycoinProject/skywire-mainnet/internal/netutil"
done

2020-02-05 07:58 UTC, Kifen commented on pkg/transport/managed_transport.go
> +// redialConn redials an underlying connection using an exponetial backoff
corrected

2020-02-05 07:59 UTC, Kifen commented on pkg/transport/manager_test.go
> +	"github.com/SkycoinProject/skywire-mainnet/internal/netutil"
done

2020-02-05 08:00 UTC, Kifen commented on pkg/visor/visor_test.go
> +	"github.com/SkycoinProject/skywire-mainnet/internal/netutil"
done

2020-02-05 11:06 UTC, nkryuchkov requested changes
Great work! Please just remove the committed binaries

2020-02-05 11:07 UTC, nkryuchkov approved these changes
Actually, I haven't seen that the binaries are in the `vendor` folder, so that's OK. Maybe just running `make dep` would be great.

2020-03-03 10:18 UTC, jdknives commented
Sorry again @Kifen . But the issue tackled with this PR will be fixed in #166

2020-03-03 10:18 UTC, closed without merging