WIP: Versioned visor configs.
skycoin/skywire pull request #364
Opened 2020-05-17 13:18 UTC by evanlinjin

Fixes #362 

 Changes:	
* Moved visor conifg-related parts to a new module /pkg/visor/visorconfig.
* Introduced visorconfig.Common that contains shared fields across all config versions.
* Improved config-parsing logic.

How to test this PR:
> TODO

2020-05-19 09:31 UTC, nkryuchkov commented on ci_scripts/install-golangci-lint.sh
> +[[ -z "${GOBIN}" ]] export GOBIN=$HOME/go/bin
Would you mind putting that into an `if` statement? I think it would look easier to understand.

2020-05-19 09:31 UTC, nkryuchkov commented on cmd/skywire-cli/commands/visor/gen-config.go
> +	"github.com/SkycoinProject/skycoin/src/util/logging"
Could you please sort them?

2020-05-19 09:31 UTC, nkryuchkov commented on cmd/skywire-visor/commands/root.go
> +	_ "net/http/pprof" // nolint:gosec https://golang.org/doc/diagnostics.html#profiling
Line 3 may be removed.

2020-05-19 09:31 UTC, nkryuchkov commented on cmd/skywire-visor/commands/root.go
> +	Short: "Skywire visor.",
Is dot obligatory here?

2020-05-19 09:31 UTC, nkryuchkov commented on cmd/skywire-visor/commands/root.go
> +			log.WithError(err).Error("Failed to obtain build info.")
What do you think of changing `obtain` back to `output` because the error indicates an error while outputting build info?

2020-05-19 09:31 UTC, nkryuchkov commented on pkg/visor/init.go
> +	"github.com/SkycoinProject/skywire-mainnet/pkg/visor/visorconfig"
Not sorted.

2020-05-19 09:31 UTC, nkryuchkov commented on pkg/visor/rpc_test.go
> +	"github.com/SkycoinProject/skywire-mainnet/pkg/visor/visorconfig"
Not sorted.

2020-05-19 09:31 UTC, nkryuchkov commented on pkg/visor/visor.go
> +	"github.com/SkycoinProject/skywire-mainnet/pkg/visor/visorconfig"
Not sorted.

2020-05-19 09:31 UTC, nkryuchkov commented on pkg/visor/visorconfig/common.go
> +func NewCommon(log *logging.MasterLogger, confPath string, version string, sk *cipher.SecKey) (*Common, error) {
To reduce line length, I'd write `confPath, version string`.

2020-05-19 13:10 UTC, evanlinjin commented on cmd/skywire-cli/commands/visor/gen-config.go
> +	"github.com/SkycoinProject/skycoin/src/util/logging"
@nkryuchkov I feel like we shouldn't be spending time manually sorting imports. I know they are atrocious to look at, but let's wait until the `go generate` solution gets implemented.

2020-05-20 15:34 UTC, Darkren requested changes
Otherwise, great job? Also, could you please run latest `readmegen` to generate readme for new config?

2020-05-20 15:34 UTC, Darkren commented on pkg/visor/visorconfig/parse_test.go
> +
Could you remove this empty line please?

2020-05-21 10:27 UTC, merged