Make proxy disc generic
skycoin/skywire pull request #374
Opened 2020-05-25 16:44 UTC by Darkren

Did you run `make format && make check`?
Yes
Fixes #7 of discovery

 Changes:	
- All endpoints changed according to the changes in the #17 of discovery
- VPN discovery added to the factory

2020-05-27 10:00 UTC, nkryuchkov approved these changes
Great job!

2020-05-27 10:00 UTC, nkryuchkov commented on pkg/app/appdisc/factory.go
> +			client: servicedisc.NewClient(log, servicedisc.Config{
What do you think of extracting the config to a variable here? I think this may increase readability. Can it be unified with the same config below?

2020-05-28 06:38 UTC, evanlinjin requested changes
Good job! Just some requests for some slight tweaks.

2020-05-28 06:38 UTC, evanlinjin commented on pkg/app/appdisc/factory.go
> +			client: servicedisc.NewClient(log, servicedisc.Config{
I would instead, create a closure named `newServiceDiscClient` or something. Because the `default:` target does not require a `servicedisc.Client`.

2020-05-28 06:38 UTC, evanlinjin commented on pkg/servicedisc/client.go
> +func NewClient(log logrus.FieldLogger, conf Config, sType string) *HTTPClient {
Instead of creating a new input, can we create a new field within the `servicedisc.Config` structure? Thanks!

2020-06-01 10:30 UTC, merged