Rename proxy discovery to service discovery
skycoin/skywire pull request #393
Opened 2020-06-06 11:30 UTC by nkryuchkov

2020-06-07 22:26 UTC, evanlinjin approved these changes
Very nice.

2020-06-08 09:39 UTC, jdknives requested changes

2020-06-08 09:39 UTC, jdknives commented on pkg/skyenv/values.go
> +	DefaultServiceDiscAddr     = "http://service.discovery.skywire.skycoin.com"
Please change that to service.discovery.skycoin.com

2020-06-08 09:39 UTC, jdknives commented on pkg/skyenv/values.go
>  	TestAddressResolverAddr = "http://address-resolver.skywire.cc"
New domain is `address.resolver.skywire.cc`

2020-06-08 09:39 UTC, jdknives commented on pkg/skyenv/values.go
>  	TestUptimeTrackerAddr   = "http://uptime-tracker.skywire.cc"
New domain here is `uptime.tracker.skywire.cc?`.

2020-06-10 12:20 UTC, jdknives approved these changes

2020-06-10 12:21 UTC, merged