[WIP] Route encryption
skycoin/skywire pull request #444
Opened 2020-07-17 11:05 UTC by Darkren

Did you run `make format && make check`?
Not yet
Fixes #432 

 Changes:	
- Data packets are E2E encrypted between communicating visors

2020-07-20 09:48 UTC, nkryuchkov requested changes
Great job! Just minor requests

2020-07-20 09:48 UTC, nkryuchkov commented on pkg/router/router.go
> +	rgsRaw        map[routing.RouteDescriptor]*RouteGroup      // not-yet-noise-wrapped route groups. when one of these gets wrapped, it gets removed from here
Could you please change both comments' case to sentence case?

2020-07-20 09:48 UTC, nkryuchkov commented on pkg/router/router.go
> +	// when route group is wrapped with noise, it's put into `nrgs`. but before that,
Could you please rewrite it to the sentence case?

2020-07-20 09:48 UTC, nkryuchkov commented on pkg/router/router.go
> +		r.logger.Warnf("Desc %s already reserved, skipping...")
Missed arg for `%s`

2020-07-20 09:48 UTC, nkryuchkov commented on pkg/router/router_test.go
> +		//RouteFinder:      rfclient.NewMock(),
Have you forgotten to uncomment it or may this line be completely removed?

2020-07-21 08:36 UTC, jdknives commented
@Darkren do you want to do that in a separate PR or should we remove encryption logic from VPN apps?

2020-07-23 06:34 UTC, evanlinjin requested changes
Good work! Tested it with local env.

Please also ensure `make check` passes.

2020-07-23 06:34 UTC, evanlinjin commented on pkg/router/router.go
> +	if ok {
I know this is not your doing, but the logic defined in lines 448 and 455 where we check for the `rule.Type()` does not make any sense to me.

I think we should either use `if` statements, or the `switch/case` statements. Not both.

Also it seems that the `RuleForward` and `RuleIntermediary` should be checked first.

2020-07-23 06:34 UTC, evanlinjin commented on pkg/router/router.go
> +	nrgs          map[routing.RouteDescriptor]*noiseRouteGroup // noise-wrapped route groups to push incoming reads from transports.
Can we rename this to `rgsNs` to be consistent? Thanks!

2020-07-23 06:34 UTC, evanlinjin commented on pkg/router/router_test.go
> +		{From: keys[1].PK, To: keys[1].PK, TpID: transport.MakeTransportID(keys[1].PK, keys[0].PK, dmsg.Type)},
Do you mean:
```golang
{From: keys[1].PK, To: keys[0].PK, TpID: transport.MakeTransportID(keys[1].PK, keys[0].PK, dmsg.Type)},
```
?

2020-07-23 06:34 UTC, evanlinjin commented on pkg/router/router_test.go
> +func Test_router_NoiseRouteGroups(t *testing.T) {
This is a rather lengthy test and a little hard to read and understand.

It would be good if we can have some summary comments describing the test as a whole and what exactly is being tested. This way one does not have to read the entire test to understand what is going on.

Thanks in advance!

2020-07-23 06:34 UTC, evanlinjin commented on pkg/router/router_test.go
> +func Test_router_NoiseRouteGroups(t *testing.T) {
It would be even better if we can break the test up into more-understandable functions.

2020-07-29 09:30 UTC, Darkren commented on pkg/router/router_test.go
> +func Test_router_NoiseRouteGroups(t *testing.T) {
@evanlinjin all parts of this test are connected, it's hard to move anything into a separate func. I'll leave comments there through the code

2020-07-29 09:39 UTC, Darkren commented
> @Darkren do you want to do that in a separate PR or should we remove encryption logic from VPN apps?

@jdknives I'll do it here. Sorry, just forgot about this

2020-07-31 15:45 UTC, nkryuchkov approved these changes

2020-08-07 19:44 UTC, merged