Add NetworkProbe to switch case expression.
skycoin/skywire pull request #597
Opened 2020-11-06 13:59 UTC by taras-skycoin

Did you run `make format && make check`?
yes
Fixes #

 Changes:	
-	Allow to route NetworkProbePackat

How to test this PR:
You need to set up a test environment.

2020-11-07 12:56 UTC, jdknives requested changes
This change alone won't do. What happens is that Network Probe packets get forwarded but the remote visor identifies them as data packets and therefore forwards them to the application using the route. This causes problems. 

<img width="1440" alt="Bildschirmfoto 2020-11-07 um 14 53 08" src="https://user-images.githubusercontent.com/36450093/98441815-6225d180-2109-11eb-8326-29ad9689d3c8.png">

2020-11-10 12:02 UTC, jdknives requested changes
Good job. This fixed the issues with `NetworkProbe` packets being forwarded to applications. Before we merge, if this PR is related to this issue 

<img width="1041" alt="Bildschirmfoto 2020-11-10 um 13 59 44" src="https://user-images.githubusercontent.com/36450093/98671663-461a6e00-235d-11eb-8045-d739b36095c9.png">

Please try to reproduce this warning on Visor B in integration env. @taras-skycoin

2020-11-10 12:06 UTC, jdknives approved these changes
Just checked and the error is not related to your PR. Can be merged after one more review.

2020-11-12 09:44 UTC, nkryuchkov approved these changes

2020-11-12 12:31 UTC, merged