Add update-config command to visor-cli.
skycoin/skywire pull request #621
Opened 2020-11-27 13:14 UTC by taras-skycoin

Did you run `make format && make check`?
yes
Fixes #610 

 Changes:	
- Add update-config command to visor-cli.

How to test this PR:
1. Run one of next possible commands:
```
go run cmd/skywire-cli/skywire-cli.go visor update-config -r
go run cmd/skywire-cli/skywire-cli.go visor update-config -e production
go run cmd/skywire-cli/skywire-cli.go visor update-config -e testing
go run cmd/skywire-cli/skywire-cli.go visor update-config --hypervisor-pks=023d1dc11119a7e2d2207f6c9e94ee88a5801702616ca1ff72bc3b2af785b7c1b8,023d1dc11119a7e2d2207f6c9e94ee88a5801702616ca1ff72bc3b2af785b7c1b8
```

2020-11-27 15:05 UTC, Darkren requested changes
Great job! I'm mostly concerned about formatting. Except one thing. Lines 82-88 and 92-97, here we store constant values to config fields. And we also do something similar while generating config. If we need to introduce a new field, we may miss it here or there. What do you think about moving these parts to separate funcs and calling these here and in the generation routines?

2020-11-27 15:05 UTC, Darkren commented on cmd/skywire-cli/commands/visor/update-config.go
> +		conf, ok := visorconfig.Parse(mLog, addInput, raw)
Could you please add an empty line before this one?

2020-11-27 15:05 UTC, Darkren commented on cmd/skywire-cli/commands/visor/update-config.go
> +
Could you please remove this empty line?

2020-11-27 15:05 UTC, Darkren commented on cmd/skywire-cli/commands/visor/update-config.go
> +
And this empty line

2020-11-27 15:05 UTC, Darkren commented on cmd/skywire-cli/commands/visor/update-config.go
> +		if environment == "production" {
Could you please add an empty line before this one?

2020-11-27 15:05 UTC, Darkren commented on cmd/skywire-cli/commands/visor/update-config.go
> +		if resetHypervisor {
Could you please add an empty line before this one?

2020-11-27 15:05 UTC, Darkren commented on cmd/skywire-cli/commands/visor/update-config.go
> +		// Save config to file.
Could you please add an empty line before this one?

2020-11-27 15:06 UTC, i-hate-nicknames commented
Great job!

I would make one file to be a target, instead of input/output, in my opinion update-config implies that there is something to which we perform the update action and the result stays there. On the other hand, having a default value for both makes it relatively easy to use as it is. 

Also, to make it more consistent with get-config command I would abstain from using -r flag, since it has different meaning in gen-config.  Instead, I would use something like `--append-hypervisor-pks` to add new PKs to existing hypervisors field, and use `--hypervisor-pks` to simply replace current list.

What do you think?

2020-11-30 12:10 UTC, taras-skycoin commented
@i-hate-nicknames  @Darkren Thank you, guys. I have added suggested changes. Please review it again when you have time.

2020-12-04 13:37 UTC, jdknives approved these changes

2020-12-04 13:48 UTC, merged