Mac installer
skycoin/skywire pull request #889
Opened 2021-09-23 02:26 UTC by alexadhy

Did you run `make format && make check`? yes

For Skywire-Visor Release 0.5.0-rc*

 Changes:	
- Package skywire-visor as macos application

TODO:
- [ ] Fix application not installed correctly 
- [ ] Fix application icon not showing properly on dock

2021-09-23 09:18 UTC, alexadhy commented
Instruction to run it:


https://user-images.githubusercontent.com/72057554/134482811-6ab95803-e3b7-465c-a914-65bf4e67f160.mp4

2021-09-23 15:12 UTC, alexadhy commented
App Icon should be working just fine now:

<img width="485" alt="Screen Shot 2021-09-23 at 22 12 14" src="https://user-images.githubusercontent.com/72057554/134534304-a992a527-6d42-4a59-801a-9a9497ef3bf8.png">

2021-09-28 08:19 UTC, alexadhy commented
Last few commits fixes privileges on macos installer and application runner

2021-09-28 11:55 UTC, jdknives reviewed
I have sent the error log of the installation on Element.

Two more points:

1. Is it possible to make Apple use the version we embed in the binary or do we have to set that somewhere dfiferently. 
2. There is an option to set a readme for the installer. What is that used for or how would the user pull that up on Apple?

2021-09-28 11:55 UTC, jdknives commented on scripts/mac_installer/create_installer.sh
> +  make CGO_ENABLED=1 GOOS=darwin GOARCH="${go_arch}" build-systray
We are not bundling any binaries other than Skywire-VPN client and visor, right? Maybe easier to build them explicitly.

2021-09-28 16:45 UTC, alexadhy commented
> I have sent the error log of the installation on Element.
> 
> 
> 
> Two more points:
> 
> 
> 
> 1. Is it possible to make Apple use the version we embed in the binary or do we have to set that somewhere dfiferently. 
> 
We can, I'll dynamically generate it / add it to the Info.plist

> 2. There is an option to set a readme for the installer. What is that used for or how would the user pull that up on Apple? 

We can via rtf files converted to b64 image iIrc, will investigate and do it if needed.

2021-09-29 17:23 UTC, jdknives requested changes

2021-09-29 17:23 UTC, jdknives commented on cmd/skywire-visor/commands/root.go
> +	defaultConfigName    = "skywire-visor.json"
This should not be changed. We should stick with `skywire-config` please.

2021-09-29 17:25 UTC, jdknives commented on cmd/skywire-visor/commands/root.go
> +	defaultConfigName    = "skywire-visor.json"
OK. Some issue with the Github interface. My bad.

2021-10-16 11:14 UTC, jdknives approved these changes

2021-10-16 11:14 UTC, jdknives commented on Makefile
> +mac-installer: ## Create unsigned application
I think we should make this create a signed installer and application. Otherwise there is not much of a point to the target as we will likely only release signed installers.

2021-10-16 11:14 UTC, jdknives commented on cmd/skywire-cli/commands/config/gen.go
> +				configName = "skywire-visor.json"
Please name it `skywire-config.json`. We should try to get all installations methods homogenized with these values and technically we are exposing the hypervisor UI.

2021-10-16 11:14 UTC, jdknives commented on internal/gui/gui.go
>  	//mVPNClient      *systray.MenuItem
I guess a lot of the commented variables here will be used for the advanced systray?

2021-10-16 11:14 UTC, jdknives commented on internal/gui/gui.go
> +func GetOnGUIReady(icon []byte, conf *visorconfig.V1, vis *visor.Visor) func() {
I dont think we should pass around the visor. The VPN UI link can be available whether or not the application has started imo. Pretty sure the UI does not require the VPN to be started in order to run correctly.

2021-10-16 11:14 UTC, jdknives commented on scripts/mac_installer/create_installer.sh
> +  amd64)
This seems to be incorrect. In case of `amd64` we set `go_arch` to `arm64`. Or am I missing anything here?

2021-10-16 13:08 UTC, alexadhy commented on internal/gui/gui.go
>  	//mVPNClient      *systray.MenuItem
Yes, it will be used for #860 (connecting to vpn via systray, show available vpn servers, etc).

2021-10-16 13:08 UTC, alexadhy commented on scripts/mac_installer/create_installer.sh
> +  amd64)
in the case of `amd64` we also create `arm64` and vice versa (we called the `build_installer` function twice basically. One for current arch and the other for the other arch.

2021-10-18 10:28 UTC, jdknives approved these changes

2021-10-18 10:29 UTC, merged