Parity between UI and CLI
skycoin/skywire pull request #981
Opened 2021-10-28 09:36 UTC by mrpalide

Did you run `make format && make check`? Yes

Fixes #920

 Changes:	
- Add `summary` command as `skywire-cli visor summary`
- Add `update` command as `skywire-cli visor update`
- Add `BUILDTAG` to skywire-cli on goreleaser.

**How to test this PR**:
- **summary**: 
  - Run `skywire-cli visor summary`.
- **update**: 
  - Build with skybian *BUILDTAG* flag `make build BUILDTAG=skybian`.
  - Run `skywire-cli visor update` to update visor.
  - (Because of no *BUILDTAG* set on skywire-cli v0.5.1) Build with skybian *BULDTAG* again.
  - Run `skywire-cli visor update` to get message about visor has the latest version.
  - For get error on non-skybian *BUILDTAG*, make build without flag and run update command. Now should get unable to update because of non-skybian *BUILDTAG*.
- **config**
  - Multiple flags added to change their values on config file. Listed as bellow:
    - `vpn-client-killswitch`: could be *true* or *false*.
    - `add-vpn-client-server`: add vpn server address to vpn-client.
    - `add-vpn-client-passcode`: add passcode of vpn server to vpn-client.
    - `reset-vpn-client`: reset all config of vpn-client.
    - `add-vpn-server-passcode`: add passcode for vpn-server.
    - `vpn-server-secure`: could be *true* or *false*.
    - `reset-vpn-server`: reset all config of vpn-server.
    - `add-skysocks-client-server`: add skysocks server pk to skysocks-client.
    - `reset-skysocks-client`: reset skysocks-client config.
    - `add-skysocks-passcode`: set passcode for skysocks server.
    - `reset-skysocks`: reset skysocks server config.
    - `set-public-autoconnect`: could be *true* or *false*.
    - `set-minhop`: should be an integer number greater equal 0.

2021-10-28 10:22 UTC, 0pcom commented
Nice work, happy to see this PR

2021-10-28 15:23 UTC, mrpalide commented
> Nice work, happy to see this PR

Please review this, and posted me about your opinion or needed commands.

2021-10-29 02:48 UTC, alexadhy requested changes
Need some changes at how to add skybian flags

2021-10-29 02:48 UTC, alexadhy commented on .goreleaser.yml
> +    ldflags: -s -w -X github.com/skycoin/dmsg/buildinfo.version=v{{.Version}} -X github.com/skycoin/dmsg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/dmsg/buildinfo.date={{.Date}} -X githu
the skybian tag should not be here for all releases, I think macOS and amd64 variant of Linux aren't part of skybian right?

2021-10-29 10:02 UTC, jdknives commented on .goreleaser.yml
> +    ldflags: -s -w -X github.com/skycoin/dmsg/buildinfo.version=v{{.Version}} -X github.com/skycoin/dmsg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/dmsg/buildinfo.date={{.Date}} -X githu
@alexadhy you are right I guess. They are not. Can we use the build tag `$OS-binary` for them?

2021-10-29 10:04 UTC, mrpalide commented on .goreleaser.yml
> +    ldflags: -s -w -X github.com/skycoin/dmsg/buildinfo.version=v{{.Version}} -X github.com/skycoin/dmsg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/dmsg/buildinfo.date={{.Date}} -X githu
We should separate them on goreleaser, right?

2021-10-31 10:27 UTC, 0pcom commented
> > Nice work, happy to see this PR
> 
> Please review this, and posted me about your opinion or needed commands.

I need the dmsgpty-cli terminal as an available subcommand in skywire-cli to have an alternative to a ssh session in order to access the visors and do manual updates, via skywire. This should also be good for general troubleshooting of running visors, right?

I know that there more to do in dmsg repo before this can happen, as @jdknives had pointed out before.

the dmsgpty-ui is already implemented in the hypervisor interface as the 'full terminal', so it seems that the dmsgpty-cli could be in skywire-cli similarly..

2021-11-02 16:57 UTC, mrpalide commented
**Updates**:
- add `H` flag to `conifg gen` for use old hypervisors list in new config.
- add `hvpk` to get pubkeys from config by `skywire-cli visor hvpk`
- for both `pk` and `hvpk` on `skywire-cli visor`, if set `-i` flag as path of config, will return directed from file and not use rpc request to online visor. It is usable for offline visor.

2021-11-04 14:04 UTC, jdknives requested changes

2021-11-04 14:04 UTC, jdknives commented on .goreleaser.yml
> +    ldflags: -s -w -X github.com/skycoin/dmsg/buildinfo.version=v{{.Version}} -X github.com/skycoin/dmsg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/dmsg/buildinfo.date={{.Date}} -X githu
https://goreleaser.com/customization/build/#build-hooks Lets use the `.Target` variable and we will separate whether or not the target is Skybian in the frontend.

2021-11-04 14:04 UTC, jdknives commented on cmd/skywire-cli/commands/config/gen.go
> +	genConfigCmd.Flags().BoolVarP(&replaceHypervisors, "use-old-hypervisors", "H", false, "use old hypervisors keys.")
Why not a lowercase `h` here? We dont use capitalized flags anywhere else here.

2021-11-04 14:04 UTC, jdknives commented on cmd/skywire-cli/commands/config/update.go
> +	minhops                int
Please capitalize `Hops`.

2021-11-04 14:04 UTC, jdknives commented on cmd/skywire-cli/commands/config/update.go
> +	updateConfigCmd.Flags().BoolVar(&resetSkysocksClient, "reset-skysocks-client", false, "reset skysocks-client's configuration")
`'s` can be removed.

2021-11-04 14:04 UTC, jdknives commented on cmd/skywire-cli/commands/config/update.go
> +	updateConfigCmd.Flags().StringVar(&setVPNClientKillswitch, "vpn-client-killswitch", "", "change killswitch status of vpn-client")
Why is that a string istead of a bool? Same question for the other values we set as bools internally such as `autoconect` and `secure` value

2021-11-04 14:04 UTC, jdknives commented on cmd/skywire-cli/commands/config/update.go
> +	updateConfigCmd.Flags().StringVar(&setVPNClientKillswitch, "vpn-client-killswitch", "", "change killswitch status of vpn-client")
Is it because you want to avoid the boolean default value?

2021-11-04 14:07 UTC, mrpalide commented on cmd/skywire-cli/commands/config/update.go
> +	updateConfigCmd.Flags().StringVar(&setVPNClientKillswitch, "vpn-client-killswitch", "", "change killswitch status of vpn-client")
Yes, was related to default value problem. Cobra has `isChanged()` method, but tbh I couldn't use it correctly, so I use string instead.

2021-11-04 14:10 UTC, mrpalide commented on cmd/skywire-cli/commands/config/update.go
> +	minhops                int
Done.

2021-11-04 14:51 UTC, mrpalide commented on cmd/skywire-cli/commands/config/gen.go
> +	genConfigCmd.Flags().BoolVarP(&replaceHypervisors, "use-old-hypervisors", "H", false, "use old hypervisors keys.")
`h` is default flag for help command. I change `H` to `x` here.

2021-11-04 16:22 UTC, jdknives approved these changes

2021-11-08 09:51 UTC, ersonp commented
Getting this panic
```
erson@erson-69:~/Workspace/Go/skywire$ ./skywire-cli config update --vpn-client-killswitch false
[2021-11-08T15:17:02+05:30] INFO [visor:config]: Flushing config to file. config_version="v1.1.0" filepath="skywire-config.json"
panic: runtime error: index out of range [3] with length 0

goroutine 1 [running]:
github.com/skycoin/skywire/cmd/skywire-cli/commands/config.changeAppsConfig(0xc00031a000, 0x9cf67f, 0xa, 0x9d002b, 0xc, 0x7ffe8bb371a6, 0x5)
        /home/erson/Workspace/Go/skywire/cmd/skywire-cli/commands/config/update.go:216 +0x3a5
github.com/skycoin/skywire/cmd/skywire-cli/commands/config.glob..func4(0xe0fbc0, 0xc000212540, 0x0, 0x2)
        /home/erson/Workspace/Go/skywire/cmd/skywire-cli/commands/config/update.go:128 +0xfe5
github.com/spf13/cobra.(*Command).execute(0xe0fbc0, 0xc000212520, 0x2, 0x2, 0xe0fbc0, 0xc000212520)
        /home/erson/Workspace/Go/skywire/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xe0f3e0, 0xc000000180, 0xc0000f9f78, 0x407f25)
        /home/erson/Workspace/Go/skywire/vendor/github.com/spf13/cobra/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/erson/Workspace/Go/skywire/vendor/github.com/spf13/cobra/command.go:887
github.com/skycoin/skywire/cmd/skywire-cli/commands.Execute()
        /home/erson/Workspace/Go/skywire/cmd/skywire-cli/commands/root.go:30 +0x31
main.main()
        /home/erson/Workspace/Go/skywire/cmd/skywire-cli/skywire-cli.go:8 +0x25
```
Whenever commands are used in the following order
```
$ ./skywire-cli config update --vpn-client-killswitch true
$ ./skywire-cli config update --add-vpn-client-server 031a5d05797d18ecf13e6f29029b0c27a1a26117467a98ff21df70cc3ddf7a20f2
$ ./skywire-cli config update --vpn-client-killswitch false
$ ./skywire-cli config update --add-vpn-client-server 0357414c43a92075758ed889ec29997e2c16ba34bf873f76e8dae2edd7b9b97122
```

2021-11-08 09:57 UTC, ersonp commented
No error is given when
```
./skywire-cli config update --vpn-client-killswitch asdsad
```
anything other than `true` or `false` is given.

2021-11-08 10:06 UTC, ersonp commented
```
./skywire-cli config update --vpn-server-secure true
```
```
./skywire-cli config update --add-vpn-server-passcode testpass
```
not reflected in config
```json
{
     "name": "vpn-server",
     "args": [
     "--passcode",
     ""
     ],
     "auto_start": false,
     "port": 44
}
```

2021-11-08 10:28 UTC, ersonp approved these changes

2021-11-08 19:25 UTC, merged